name = "gsmp5"
author = "GSMP Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb256aaf16211eca23b9f5757b8fdff7df9316062083ce6fee7f37e8f7b023fd"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
