name = "gsmp5"
author = "GSMP Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfe37aefa5f1911c27b4a5953de8536873e3aee80342d05624ca8fe735134d7c"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
