name = "gsmp5"
author = "GSMP Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90ba6b1c2fe4309e9b9d2dd52897cd2c0cc18ead98b57d763bb04daf390c4ce2"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
