name = "gsmp5"
author = "GSMP Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db4e8d357e23e5f85e4277226cfe75e334555d6ad492403087d6e5c8f69badfb"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
