name = "gsmp5"
author = "GSMP Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd53f7646342d9ce58b5fae657d4b5dd9d28041a64c0ad20f252137ee373cf9a"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
