name = "gsmp5"
author = "GSMP Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56e9aef03627bf7a7d27309cd8b094aa46ae62b268472638669c617bbf366131"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
