name = "gsmp5"
author = "GSMP Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1d318ee57adaa00347c73bc04b236db9fae829d6752bb280059381744973ebf"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
